add Update#sourceUser method
InsanusMokrassar/TelegramBotAPI pull request #422
Opened 2021-06-28 17:35 UTC by eboshare

- Added Update#sourceUser method

2021-06-28 18:13 UTC, InsanusMokrassar requested changes
Нужно проверить, часто, например, обновления с сообщениями могут быть в чат, но от пользователя (asFromUser)

2021-06-28 18:13 UTC, InsanusMokrassar commented on tgbotapi.extensions.utils/src/commonMain/kotlin/dev/inmo/tgbotapi/extensions/utils/extensions/UpdateChatRetriever.kt
> +        is SentMediaGroupUpdate -> data.chat?.asUser()
Добавить `?: first().asFromUserMessage().user`

2021-06-28 18:13 UTC, InsanusMokrassar commented on tgbotapi.extensions.utils/src/commonMain/kotlin/dev/inmo/tgbotapi/extensions/utils/extensions/UpdateChatRetriever.kt
> +        is EditMediaGroupUpdate -> data.chat.asUser()
добавить `?: asFromUserMessage().user`

2021-06-28 18:37 UTC, InsanusMokrassar commented
Я предлагаю сделать следующее - для данных если это не медиа группа сделать asFromUser (хотя я не уверен, что получится), потом попробовать достать чат (sourceChat) и сделать для него asUser

2021-06-28 18:39 UTC, InsanusMokrassar commented
В идеале в рамках PR еще надо проверить, что все типы, которые имеют пользователя как одно из основных полей, наследуют FromUser

2021-06-28 20:22 UTC, eboshare commented
@InsanusMokrassar 
Вообще все объекты с полем `user` должны иметь тип `FromUser`?

2021-06-28 22:09 UTC, eboshare commented
@InsanusMokrassar 

> Я предлагаю сделать следующее - для данных если это не медиа группа сделать asFromUser (хотя я не уверен, что получится), потом попробовать достать чат (sourceChat) и сделать для него asUser

Не совсем понял что имеется в виду, сделать метод `asFromUser` для каких-то типов? 
Про это совсем не понял 👇
>  потом попробовать достать чат (sourceChat) и сделать для него asUser

2021-06-28 23:58 UTC, InsanusMokrassar requested changes

2021-06-28 23:58 UTC, InsanusMokrassar commented on tgbotapi.core/src/commonMain/kotlin/dev/inmo/tgbotapi/types/ChatMemberUpdated.kt
> +    override val user: User,
Это не FromUser - тут пользоваиель не признак отправителя, а всего лишь свойство события

2021-06-28 23:58 UTC, InsanusMokrassar commented on tgbotapi.core/src/commonMain/kotlin/dev/inmo/tgbotapi/types/games/GameHighScore.kt
> -    val user: User,
Тут пользователь не является источником, поэтому тоже не FromUser

2021-06-28 23:58 UTC, InsanusMokrassar commented on tgbotapi.core/src/commonMain/kotlin/dev/inmo/tgbotapi/types/payments/PreCheckoutQuery.kt
> +    override val user: User,
В идеале надо бы как-то проверить, что такое нам приходит именно по триггеру юзера

2021-06-28 23:58 UTC, InsanusMokrassar commented on tgbotapi.core/src/commonMain/kotlin/dev/inmo/tgbotapi/types/message/ChatEvents/LeftChatMember.kt
> +): CommonEvent, FromUser
Не источник, поэтому не FromUser

2021-06-28 23:58 UTC, InsanusMokrassar commented on tgbotapi.extensions.utils/src/commonMain/kotlin/dev/inmo/tgbotapi/extensions/utils/extensions/UpdateChatRetriever.kt
> +fun Update.sourceUser(): User? = when (this) {
Лучше проверять `data.asFromUser() ?.user ?: data.sourceChat().asUser()`

2021-06-29 00:00 UTC, InsanusMokrassar commented
> @InsanusMokrassar
> Вообще все объекты с полем `user` должны иметь тип `FromUser`?

Нет, только те, для которых источником является пользователь. Приватные сообщения, например:)

2021-06-29 00:38 UTC, eboshare commented on tgbotapi.extensions.utils/src/commonMain/kotlin/dev/inmo/tgbotapi/extensions/utils/extensions/UpdateChatRetriever.kt
> +fun Update.sourceUser(): User? = when (this) {
То есть в файле ClassCasts дописать нужным нам типам обновлений расширения `asFromUser`?

2021-06-29 04:24 UTC, InsanusMokrassar commented on tgbotapi.extensions.utils/src/commonMain/kotlin/dev/inmo/tgbotapi/extensions/utils/extensions/UpdateChatRetriever.kt
> +fun Update.sourceUser(): User? = when (this) {
Вообще, там можно дописать Any.asFromUser (и when, и require), хотя мне казалось, он уже есть

2021-06-29 05:58 UTC, InsanusMokrassar requested changes

2021-06-29 05:58 UTC, InsanusMokrassar commented on tgbotapi.core/src/commonMain/kotlin/dev/inmo/tgbotapi/types/InlineQueries/ChosenInlineResult/RawChosenInlineResult.kt
> +) : FromUser {
Это internal, тут FromUser не нужен

2021-06-29 05:58 UTC, InsanusMokrassar commented on tgbotapi.core/src/commonMain/kotlin/dev/inmo/tgbotapi/types/InlineQueries/abstracts/ChosenInlineResult.kt
> +interface ChosenInlineResult : FromUser {
Стяни себе изменения, я переместил этот интерфейс

2021-06-29 05:58 UTC, InsanusMokrassar commented on tgbotapi.core/src/commonMain/kotlin/dev/inmo/tgbotapi/types/message/ChatEvents/LeftChatMember.kt
> +import dev.inmo.tgbotapi.CommonAbstracts.FromUser
Лишнее

2021-06-29 05:58 UTC, InsanusMokrassar commented on tgbotapi.core/src/commonMain/kotlin/dev/inmo/tgbotapi/types/games/GameHighScore.kt
> +data class GameHighScore(
Лишнее изменение

2021-06-30 04:34 UTC, InsanusMokrassar approved these changes

2021-06-30 04:39 UTC, merged