New docs
InsanusMokrassar/TelegramBotAPI pull request #458
Opened 2021-09-08 22:10 UTC by ggoraa

Начал процесс добавления KDocs в код

2021-09-08 22:15 UTC, ggoraa commented
Сразу скажу, коммиты помечены как Unverified потому что я добавлял доки из VS Code Web, типо по нажатию точки на странице репы, и я еще не разобрался как включить подпись коммитов там

2021-09-09 10:45 UTC, InsanusMokrassar commented
You may mark this PR as a draft if it is still in progress

2021-09-10 14:21 UTC, InsanusMokrassar requested changes

2021-09-10 14:21 UTC, InsanusMokrassar commented on tgbotapi.extensions.api/src/commonMain/kotlin/dev/inmo/tgbotapi/extensions/api/send/SendAction.kt
> + * Displays nice "typing" text in chat header
nice -> action

2021-09-10 14:21 UTC, InsanusMokrassar commented on tgbotapi.extensions.api/src/commonMain/kotlin/dev/inmo/tgbotapi/extensions/api/send/SendAction.kt
> + * Displays some nice "typing" text in chat header
nice -> action

2021-09-10 14:21 UTC, InsanusMokrassar commented on tgbotapi.extensions.api/src/commonMain/kotlin/dev/inmo/tgbotapi/extensions/api/send/media/SendDocument.kt
> + * @param disableContentTypeDetection - idk
Add several `@see`

2021-09-10 14:21 UTC, InsanusMokrassar commented on tgbotapi.extensions.api/src/commonMain/kotlin/dev/inmo/tgbotapi/extensions/api/send/media/SendDocument.kt
> + * @param allowSendingWithoutReply - idk
Replace with `Avoid errors when replyId message was deleted in the chat`

2021-09-21 10:27 UTC, InsanusMokrassar commented
Closing due to inactivity and inability of @ggoraa to complete this PR near time (@ggoraa correct me if I am wrong)

2021-09-21 10:27 UTC, closed without merging

2021-09-21 10:28 UTC, ggoraa commented
Yes, i am unable to do it. College 🤷